import { and, eq, inArray } from "drizzle-orm";
import { opportunityAuditDetails } from "../drizzle/auditProSchema";
import {
  activityHistory,
  amendmentRecords,
  amendmentSourceLinks,
  assignments,
  canopyTaskClusters,
  opportunityReviews,
  taxYearRecords,
  users,
} from "../drizzle/schema";
import { closeDbPool, requireDb } from "../server/db";
import { auditProRouter } from "../server/routers/auditPro";

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(message);
}

function sameNumberSet(actual: number[], expected: number[]): boolean {
  const a = Array.from(new Set(actual)).sort((x, y) => x - y);
  const b = Array.from(new Set(expected)).sort((x, y) => x - y);
  return a.length === b.length && a.every((value, index) => value === b[index]);
}

async function main() {
  const opportunityId = Number(process.argv[2] ?? "4");
  const actorEmail = String(process.argv[3] ?? "").trim().toLowerCase();

  if (!Number.isInteger(opportunityId) || opportunityId <= 0 || !actorEmail) {
    throw new Error(
      "Usage: pnpm exec tsx scripts/verify-audit-pro-db.ts <opportunityId> <active-taxace-user@taxacebsi.com>",
    );
  }

  const db = await requireDb();
  const [actor] = await db
    .select()
    .from(users)
    .where(and(eq(users.email, actorEmail), eq(users.active, true)))
    .limit(1);
  assert(actor, `Active TaxAce user not found: ${actorEmail}`);
  assert(actor.role !== "Viewer", "Audit Pro acceptance requires Admin / EA Reviewer / Preparer access.");

  const [reviewBefore] = await db
    .select()
    .from(opportunityReviews)
    .where(eq(opportunityReviews.id, opportunityId))
    .limit(1);
  assert(reviewBefore, `Opportunity Review ${opportunityId} was not found.`);
  assert(reviewBefore.active, `Opportunity Review ${opportunityId} is already inactive. Use another active opportunity.`);
  assert(reviewBefore.sourceWorkGroupId, "Acceptance verifier requires a Canopy-linked Opportunity Review.");

  const sourceClusters = await db
    .select({ taxYear: canopyTaskClusters.taxYear, returnType: canopyTaskClusters.returnType })
    .from(canopyTaskClusters)
    .where(eq(canopyTaskClusters.workGroupId, reviewBefore.sourceWorkGroupId));
  assert(sourceClusters.length > 0, "Linked Canopy work group has no logical task clusters.");

  const sourceYears = Array.from(new Set(sourceClusters.map(row => row.taxYear))).sort((a, b) => a - b);
  const returnTypes = Array.from(new Set(sourceClusters.map(row => row.returnType)));
  assert(returnTypes.length === 1, "Acceptance verifier expected one Return Type in the linked Canopy work group.");
  const amendmentType = returnTypes[0]!;

  const caller = auditProRouter.createCaller({
    user: actor,
    req: {} as any,
    res: {} as any,
  });

  const contextBefore = await caller.context({ id: opportunityId });
  assert(contextBefore.source, "Audit Pro context did not expose linked Canopy source context.");
  assert(sameNumberSet(contextBefore.source.taxYears, sourceYears), "Audit Pro source years do not match current Canopy clusters.");

  const auditFields = {
    recommendation: "Recommend Amendment" as const,
    priority: "High" as const,
    amendmentReasonSummary: "Slice 5 acceptance verification: controlled amendment creation from reviewed Canopy source facts.",
    documentsReceivedSummary: "Acceptance verification summary only; no Canopy documents are stored by Audit Pro.",
    documentsNeededSummary: null,
    amendmentAssessment: "Slice 5 acceptance verification confirms the structured human review and controlled creation workflow.",
    riskIssueNotes: "Acceptance verification risk/issue note.",
    reviewNotes: "Generated by scripts/verify-audit-pro-db.ts for local Slice 5 acceptance testing.",
    estimatedTaxImpact: 1234.56,
  };

  await caller.launch({ id: opportunityId });
  const afterLaunch = await caller.context({ id: opportunityId });
  assert(afterLaunch.opportunity.opportunityStatus === "Under Review", "Launch did not move Pending Review to Under Review.");
  assert(afterLaunch.auditDetail?.auditStartedAt, "Audit launch timestamp was not persisted.");

  await caller.save({ id: opportunityId, ...auditFields });
  const afterSave = await caller.context({ id: opportunityId });
  assert(afterSave.opportunity.amendmentReasonSummary === auditFields.amendmentReasonSummary, "Audit draft reason was not persisted.");
  assert(afterSave.auditDetail?.riskIssueNotes === auditFields.riskIssueNotes, "Audit risk/issue notes were not persisted.");

  await caller.complete({
    id: opportunityId,
    outcome: "Ready to Create Amendment",
    ...auditFields,
  });
  const afterComplete = await caller.context({ id: opportunityId });
  assert(
    afterComplete.opportunity.opportunityStatus === "Ready to Create Amendment",
    "Audit completion did not set Ready to Create Amendment.",
  );
  assert(afterComplete.auditDetail?.auditCompletedAt, "Audit completion timestamp was not persisted.");

  const created = await caller.createAmendment({
    opportunityReviewId: opportunityId,
    amendmentReason: auditFields.amendmentReasonSummary,
    amendmentAssessment: auditFields.amendmentAssessment,
    riskIssueNotes: auditFields.riskIssueNotes,
    amendmentType,
    taxYears: sourceYears.map(taxYear => ({ taxYear, jurisdiction: "Federal" as const })),
    assignedPreparerId: actor.id,
    currentOwnerId: actor.id,
    assignedEaReviewerId: null,
    priority: "High",
  });

  const [amendment] = await db
    .select()
    .from(amendmentRecords)
    .where(eq(amendmentRecords.id, created.id))
    .limit(1);
  assert(amendment, "Controlled Create Amendment did not persist an Amendment Record.");
  assert(amendment.workflowStatus === "Investigation", "New Amendment Record did not start in Investigation.");
  assert(amendment.clientId === reviewBefore.clientId, "Created Amendment Record is linked to the wrong client.");
  assert(amendment.amendmentType === amendmentType, "Created Amendment Type does not match the Canopy Return Type.");
  assert(amendment.assignedPreparerId === actor.id, "Assigned Preparer was not persisted.");
  assert(amendment.currentOwnerId === actor.id, "Current Owner was not persisted.");

  const yearRows = await db
    .select()
    .from(taxYearRecords)
    .where(eq(taxYearRecords.amendmentId, created.id));
  assert(yearRows.length === sourceYears.length, "Created Tax Year Record count does not match source years.");
  assert(sameNumberSet(yearRows.map(row => row.taxYear), sourceYears), "Created Tax Year Records do not match the Canopy source years.");
  assert(yearRows.every(row => row.jurisdiction === "Federal"), "Acceptance jurisdiction was not persisted consistently.");

  const assignmentRows = await db
    .select()
    .from(assignments)
    .where(eq(assignments.amendmentId, created.id));
  const assignmentRoles = new Set(assignmentRows.map(row => row.assignmentRole));
  assert(assignmentRows.length === 2, "Expected exactly Preparer + Current Owner assignment rows for this acceptance run.");
  assert(assignmentRoles.has("Assigned Preparer"), "Assigned Preparer assignment history row is missing.");
  assert(assignmentRoles.has("Current Owner"), "Current Owner assignment history row is missing.");

  const sourceLinks = await db
    .select()
    .from(amendmentSourceLinks)
    .where(eq(amendmentSourceLinks.amendmentId, created.id));
  assert(sourceLinks.length === 1, "Created Amendment Record must have exactly one Canopy source work-group link.");
  assert(sourceLinks[0]!.workGroupId === reviewBefore.sourceWorkGroupId, "Amendment source link points to the wrong work group.");

  const [reviewAfter] = await db
    .select()
    .from(opportunityReviews)
    .where(eq(opportunityReviews.id, opportunityId))
    .limit(1);
  assert(reviewAfter && !reviewAfter.active, "Opportunity Review was not closed after controlled creation.");
  assert(reviewAfter.amendmentOpportunity === true, "Opportunity Review was not retained as an amendment opportunity.");

  const [auditDetail] = await db
    .select()
    .from(opportunityAuditDetails)
    .where(eq(opportunityAuditDetails.opportunityReviewId, opportunityId))
    .limit(1);
  assert(auditDetail?.auditStartedAt, "Persisted Audit Pro detail is missing auditStartedAt.");
  assert(auditDetail?.auditCompletedAt, "Persisted Audit Pro detail is missing auditCompletedAt.");
  assert(auditDetail.riskIssueNotes === auditFields.riskIssueNotes, "Persisted Audit Pro risk/issue note changed unexpectedly.");

  const creationActivity = await db
    .select()
    .from(activityHistory)
    .where(
      and(
        eq(activityHistory.amendmentId, created.id),
        inArray(activityHistory.action, [
          "Amendment Record created from Audit Pro",
          "Opportunity Review completed with controlled Create Amendment",
        ]),
      ),
    );
  assert(creationActivity.length === 2, "Expected both correlated controlled-creation Activity History events.");
  assert(
    creationActivity[0]!.correlationId === creationActivity[1]!.correlationId,
    "Controlled creation Activity History entries do not share one correlation ID.",
  );

  const opportunityActivity = await db
    .select({ action: activityHistory.action })
    .from(activityHistory)
    .where(eq(activityHistory.entityId, opportunityId));
  const opportunityActions = new Set(opportunityActivity.map(row => row.action));
  assert(opportunityActions.has("Amendment Audit Pro launched"), "Audit Pro launch Activity History entry is missing.");
  assert(opportunityActions.has("Amendment Audit Pro draft saved"), "Audit Pro draft Activity History entry is missing.");
  assert(
    opportunityActions.has("Amendment Audit Pro completed: Ready to Create Amendment"),
    "Audit Pro completion Activity History entry is missing.",
  );

  console.log(`PASS: Audit Pro launched and persisted human review for Opportunity Review ${opportunityId}.`);
  console.log(`PASS: Ready to Create Amendment state enforced for source years ${sourceYears.join(", ")}.`);
  console.log(`PASS: created ${created.amendmentRecordId} in Investigation with ${yearRows.length} Tax Year Record(s).`);
  console.log("PASS: Preparer + Current Owner assignments and Canopy source link were persisted atomically.");
  console.log("PASS: Audit timestamps, risk notes, Opportunity Review closure, and correlated Activity History verified.");
  console.log("PASS: Slice 5 Amendment Audit Pro controlled creation acceptance verified end-to-end.");
}

main()
  .catch(error => {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await closeDbPool();
  });
